name: Publish to PyPI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH  # Ensure uv is in PATH

      - name: Build package
        run: uv pip compile -o dist

      - name: Publish package
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: uv pip publish --token $PYPI_TOKEN
